config/routes.rb
Rails.application.routes.draw do  
  resources :messages, only: [:new, :create]
  get 'auth/:provider/callback' , to: 'sessions#create', protect_from_forgery: false
  get 'thoat' , to: 'sessions#destroy',as: :thoat
  get 'offline',to: 'sessions#offline'
  get 'online',to: 'sessions#online'
  root 'messages#new'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :messages,dependent: :delete_all
	def self.from_omniauth(auth)
		provider = auth.provider
		uid = auth.uid
		info = auth.info.symbolize_keys!
		user = User.find_or_initialize_by(uid: uid,provider: provider)
		user.name = info.name
		user.status = true
		user.avatar_url = info.image
		user.profile_url = 'https://facebook.com/'+auth.uid
		user.save!
		user
	end
	# def self.update(status)
	#   update_attribute(:status, status)
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def current_user
	  if session[:user_id]
	  	current_user = User.find_by(id: session[:user_id]) 
	  end
  end
  helper_method :current_user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
    @messages = Message.order('created_at ASC')
    @allmessage = Message.order('created_at ASC')
    @all_user = User.order('id DESC')
    if current_user
      @user = User.find(session[:user_id])
    end
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    respond_to do |format|
      if current_user
        @message = current_user.messages.build(message_params)
        if @message.save
          flash.now[:success] = 'Your message was successfully posted!'
          format.js
        else
          flash.now[:error] = 'Your message cannot be saved.'
        end
      else
        format.js {render nothing: true}
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.from_omniauth(request.env['omniauth.auth'])
		user.status = true
		user.save
		session[:user_id] = user.id
		flash[:success] = "Chào bạn, #{user.name}"
		redirect_to root_url
	end
	def destroy
		user = User.find(session[:user_id])
		# user.update_attribute(:status, false)
		user.status = false
		user.save

		# flash[:success] = "Hẹn gặp lại !"
		respond_to do |format|
		      format.json { render json: {messages: "Offline"} }
		      format.js
		  end
		session.delete(:user_id)
	end

	def auth_fails
		render text: "Bạn đang cố gắng đăng nhập #{params[:strategy]},nhưng theo chúng tôi biết bạn đang gặp lỗi#{params[:messages]}",status: 500
	end
	def offline
		user = User.find(session[:user_id])
		# user.update_attribute(:status, false)
		user.status = false
		user.save
		render json: {
			  messages: "Offline"
			}, status: 200
	end
	def online
		user = User.find(session[:user_id])
		# user.update_attribute(:status, false)
		user.status = true
		user.save
		respond_to do |format|
			format.js
		end
		render json: {
			  messages: "Online"
			}, status: 200	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
  		<div class="col-md-12">
  			Hello,<strong><%= current_user.name %></strong>		
			&nbsp;<%= link_to raw("<i style='width:10px;height:30px;' alt='Logout' class='fa fa-sign-out'></i>"),thoat_path,remote: true %>
  		</div>
    <div style="display: none" id ="session_user"><%= session[:user_id] %></div>
  <% end %>
<%= yield %>

</body>
</html>

app/views/messages/_message.html.erb
<% if message.user_id == session[:user_id] %>
<div class="answer">
  <div class="avatar">
    <img src="<%= message.user.avatar_url %>" alt="User name">
    <div class="status online"></div>
  </div>
  <div class="name"><small><%= message.user.name %></small></div>
  <div class="text">
    <%= message.body %>
  </div>
</div>
<% else %>
<div class="answer">
  <div class="avatar">
    <img src="<%= message.user.avatar_url %>" alt="User name">
    <div class="status online"></div>
  </div>
  <div class="name"><small><%= message.user.name %></small></div>
  <div class="text">
    <%= message.body %>
  </div>
</div>
<% end %>

app/views/messages/_messages.html.erb
<% @allmessage.each do |message| %>
<% if message.user_id == session[:user_id] %>
<div class="answer right">
  <div class="avatar">
    <img src="<%= message.user.avatar_url %>" alt="User name">
    <div class="status online"></div>
  </div>
  <div class="name"><small><%= message.user.name %></small></div>
  <div class="text">
    <%= message.body %>
  </div>
</div>
<% else %>
<div class="answer left">
  <div class="avatar">
    <img src="<%= message.user.avatar_url %>" alt="User name">
    <div class="status online"></div>
  </div>
  <div class="name"><small><%= message.user.name %></small></div>
  <div class="text">
    <%= message.body %>
  </div>
</div>
<% end %>
<% end %>

app/views/messages/_user.html.erb
<div class="user <%= @user.id %>" id="<%= @user.id %>">
    <div class="avatar">
    <img src="<%= @user.avatar_url %>" alt="<%= @user.name %>">
    <div id= "<%= @user.id %>" class="<% if @user.status == true %> status online <% else %> status offline <% end %>"></div>
    </div>
    <div class="name name-cl"><%= link_to @user.name,@user.profile_url,target: "_blank" %></div>
    <div class="mood"><% if @user.status == true %> Đang online <% else %> Offline <% end %></div>
</div>

app/views/messages/_users.html.erb
<% @all_user.each do |user| %>
<div class="user <%= user.id %>" id="<%= user.id %>">
    <div class="avatar">
    <img src="<%= user.avatar_url %>" alt="<%= user.name %>">
    <div id= "<%= user.id %>" class="<% if user.status == true %> status online <% else %> status offline <% end %>"></div>
    </div>
    <div class="name name-cl"><%= link_to user.name,user.profile_url,target: "_blank" %></div>
    <div class="mood"><% if user.status == true %> Đang online <% else %> Offline <% end %></div>
</div>
<% end %>

app/views/messages/create.js.erb
// publisher = client.publish('/messages', {
//   message: '<%= j render @message  %>'
// });

// publisher.callback(function() {
	 //  var t = $('#bb .answer');
  // // console.log('...',$('#bb').scrollTop(t.length * $(t).first().height() + 50))
  // // var t = $('#bb .answer');
  // $('#bb').scrollTop(t.length * $(t).first().height() + 50);
  // // console.log('....',t.length * $(t).first().height() + 50)
  // $('#message_body').val('');
  // $('#message_body').attr('disabled',false);
  // $('.send-btn').html('Send')
  // $('#message_body').focus();
  // $('#new_message').find("input[type='submit']").val('Submit').prop('disabled', false)
// });

// publisher.errback(function() {
//   alert('There was an error while posting your comment.');
// });
<% publish_to "/messages" do %>
  var testcm = $('#tcm').text();
  $('.chat-body').append('<%= j render @message  %>');
  if(testcm == 'b'){
  $('#bb .answer').last().addClass('right');
  $('#tcm').empty();
  }
  else
  $('#bb .answer').last().addClass('left');
  var t = $('#bb .answer');
  $('#bb').scrollTop(t.length * $(t).first().height() + 50);
<% end %>
  var t = $('#bb .answer');
// console.log('...',$('#bb').scrollTop(t.length * $(t).first().height() + 50))
// var t = $('#bb .answer');
$('#bb').scrollTop(t.length * $(t).first().height() + 50);
// console.log('....',t.length * $(t).first().height() + 50)
$('#message_body').val('');
$('#message_body').attr('disabled',false);
$('.send-btn').html('Send')
$('#message_body').focus();
$('#new_message').find("input[type='submit']").val('Submit').prop('disabled', false)

app/views/messages/new.html.erb
<% if current_user %>
<div class="content container-fluid bootstrap snippets">
      <div class="row row-broken">
        <div class="col-sm-3 col-xs-12">
          <div class="col-inside-lg decor-default chat" style="overflow: hidden; outline: none;" tabindex="5000">
            <div class="chat-users" id = "users">
            <%= render 'users' %>
                
<!--                 <div class="user">
                    <div class="avatar">
                    <img src="http://bootdey.com/img/Content/avatar/avatar2.png" alt="User name">
                    <div class="status online"></div>
                    </div>
                    <div class="name">User name</div>
                    <div class="mood">User mood</div>
                </div>
                <div class="user">
                    <div class="avatar">
                    <img src="http://bootdey.com/img/Content/avatar/avatar3.png" alt="User name">
                    <div class="status busy"></div>
                    </div>
                    <div class="name">User name</div>
                    <div class="mood">User mood</div>
                </div> -->
            </div>
          </div>
        </div>
        <div id="aa" class="col-sm-9 col-xs-12 chat" style="overflow: hidden; outline: none;" tabindex="5001">
          <div id="bb" class="col-inside-lg decor-default chat">
            <div id="c" class="chat-users chat-body">
              <%= render 'messages' %>
            	</div>
            </div>
          </div>
        </div>
      <div class="col-sm-12 col-xs-12 col-md-12">
         <div class="answer-add">
                  <%= form_for @message,remote: true do |f| %>
                  <div class="input-group">
                      <%= text_area :message,:body ,rows: 1,placeholder: 'Type a message', class: 'form-control' %>
                      <%= f.submit style:'display:none',id: 'submit-message' %>
                      <span class="input-group-btn">
                        <button class="send-btn btn btn-default" type="button">Send</button>
                      </span>
                  </div>
                  <% end %>
                  <%= subscribe_to "/messages" %>
                  <%= subscribe_to "/thoat" %>
                  <%= subscribe_to "/auth/facebook" %>
          </div>
      </div>
      </div>
<script type="text/javascript">
$(function(){
    $(".chat").niceScroll();
    // <% if(session[:user_id]) %>
    // publisher = client.publish('/facebook',{Status: "<%= session[:user_id] %>"})
    // publisher.callback(function(){
    //   return true;
    // });
    // publisher.errback(function(){
    //   console.log("Error online");
    // });
    // <% end %>
    <% publish_to "/auth/facebook" do %>
      if($('.user').hasClass('<%= session[:user_id] %>')) {
        console.log($('.user').attr('id'));
        // console.log('<%= session[:user_id] %>');
        $('#<%= session[:user_id] %> .mood').html('Đang online');
        $('#<%= session[:user_id] %> .status').removeClass('offline');
        $('#<%= session[:user_id] %> .status').addClass('online');

      }
      else{
          $('#users').prepend('<%= j render 'user' %>')
        }
    <% end %>
})
</script>
<div id="tcm" style="display: none"></div>
<% else %>
<main>
    <div class="container">
      <div class="component">
        <div class="row"> 
          <div class="col-md-12 text">Login</div> 
        </div>
        <%= link_to 'facebook', '/auth/facebook',class: "icon icon-mono facebook"%>
        <a href="#" class="icon icon-mono twitter">twitter</a>
        <a href="#" class="icon icon-mono googleplus">google+</a>
        <a href="#" class="icon icon-mono github">github</a>
        <a href="#" class="icon icon-mono rss">rss</a>
      </div>
    </div>
</main>
<% end %>